In [13]:
#2D arrays
import numpy as np
a = np.zeros((5,7),dtype=np.int)
print(a)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [14]:
for i in range(len(a)):
    for j in range(len(a[i])):
        a[i,j] = i+j
print(a)

[[ 0  1  2  3  4  5  6]
 [ 1  2  3  4  5  6  7]
 [ 2  3  4  5  6  7  8]
 [ 3  4  5  6  7  8  9]
 [ 4  5  6  7  8  9 10]]


In [15]:
b = np.copy(a)
b[:,2] = -100
print(b)

[[   0    1 -100    3    4    5    6]
 [   1    2 -100    4    5    6    7]
 [   2    3 -100    5    6    7    8]
 [   3    4 -100    6    7    8    9]
 [   4    5 -100    7    8    9   10]]


In [16]:
c = np.ones((7,5))
print(a@c)

[[21. 21. 21. 21. 21.]
 [28. 28. 28. 28. 28.]
 [35. 35. 35. 35. 35.]
 [42. 42. 42. 42. 42.]
 [49. 49. 49. 49. 49.]]


In [4]:
import numpy as np
import math

In [5]:
math.exp(np.linspace(0,1,100))

TypeError: only size-1 arrays can be converted to Python scalars